// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfmcscltlllnywxhdhar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmbWNzY2x0bGxsbnl3eGhkaGFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODQyODksImV4cCI6MjA2ODY2MDI4OX0.3cN4xQ-hrscjV4pv4N7kkQm3HcvVa6TtXrC66JILBGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});